name: Laravel Docker Image With PHP 8.2 Base On DPTSI Image CI

on:
  push:
    branches: none # [ "main" ]
  pull_request:
    branches: none # [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build & Push laravel docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check location
        run: |
          ls -la
          pwd
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./8.2-dptsi-grpc
          file: ./8.2-dptsi-grpc/Dockerfile
          push: true
          tags: mirzaq19/laravel-docker-image:8.2
